### ISSUE TITLE
Feature Request - MX Priority

### ISSUE THREAD

**Issue by Pilly170** [ndejong/domain-email-records#1]
Hi,

Thanks for this tool.
Is it possible to add Mx Priority?
Also is dkim possible?

**Comment by ndejong** [comment]
Yes - the `mx_preference` value been added in version `0.4.2` just now

No - dkim cannot be added since there is no way to know the dkim selector without receiving an email in order to observe the selector - at best one might implement some kind of selector guessing or well-known selector value lookup
